site_name: PYTHUSA
site_description: Python-first shared-memory DSP pipelines
site_url: https://daciwolf.github.io/pythusa/
repo_url: https://github.com/daciwolf/pythusa
repo_name: daciwolf/pythusa

theme:
  name: mkdocs

nav:
  - Home: index.md
  - Pipeline API: pipeline.md
  - Runtime: runtime.md
  - Benchmarks: benchmarks.md
